### PR TITLE
Raise an exception when input is empty

### PR DESCRIPTION
**Pull request by abhinandanudupa**

### CODE REVIEW

**Comment by abhinandanudupa** [comment]
Helps one to identify the issue when a cryptic error like this is raised (if an empty string is passed as the input):

```bash
<redacted>/node_modules/google-translate-api-x/lib/translation/batchTranslate.cjs:110
                                if (translation[1][0][0][5] === undefined || translation[1][0][0][5] === null) {
                                               ^

TypeError: Cannot read properties of null (reading '1')
    at <redacted>/node_modules/google-translate-api-x/lib/translation/batchTranslate.cjs:110:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async translateText (<redacted>/translation/translateHelpers.js:60:22)
    at async translate
```

**Comment by AidanWelch** [comment]
I appreciate you working on this, and fixing it.  But from my perspective I think it makes more sense to just return an empty string as the expected result, rather than error on certain valid string inputs just because its not what the API expects.

**Comment by abhinandanudupa** [comment]
I did think of that approach but I wasn't sure of fill in the other fields of the result object. So I did not pursue it.

> I appreciate you working on this, and fixing it. But from my perspective I think it makes more sense to just return an empty string as the expected result, rather than error on certain valid string inputs just because its not what the API expects.

It's all right.

Thank you!

**Comment by abhinandanudupa** [comment]
Now, it's obviously too late but my reasoning for raising an error is why would anyone want to translate an empty string and when processing user input it may be hard to figure out the reason for the error/empty (string as of now).

I don't know why I did not tell about this before.

**Comment by AidanWelch** [comment]
I don't know.  I was thinking, someone may want to translate an array of strings that they don't necessarily know if they're empty or not- and it would just be a pointless hassle for them to check for empty.  After all, an empty string is still a valid string

**Comment by abhinandanudupa** [comment]
> I don't know. I was thinking, someone may want to translate an array of strings that they don't necessarily know if they're empty or not- and it would just be a pointless hassle for them to check for empty. After all, an empty string is still a valid string

I agree, I just wanted to put this across as I felt that I hadn't done a good job explaining the PR. Either way it is now easier deal with the situation. :)

**Pull request merged**
